// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/com/zc/messages/player/ListMoneyHistoryRsp.proto

package com.zc.web.message.player;

public final class ListMoneyHistoryRspProto {
  private ListMoneyHistoryRspProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ListMoneyHistoryRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;
    /**
     * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
     */
    java.util.List<com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg> 
        getHistoryList();
    /**
     * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
     */
    com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg getHistory(int index);
    /**
     * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
     */
    int getHistoryCount();
    /**
     * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
     */
    java.util.List<? extends com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsgOrBuilder> 
        getHistoryOrBuilderList();
    /**
     * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
     */
    com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsgOrBuilder getHistoryOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.zc.web.message.player.ListMoneyHistoryRsp}
   */
  public static final class ListMoneyHistoryRsp extends
      com.google.protobuf.GeneratedMessage
      implements ListMoneyHistoryRspOrBuilder {
    // Use ListMoneyHistoryRsp.newBuilder() to construct.
    private ListMoneyHistoryRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ListMoneyHistoryRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ListMoneyHistoryRsp defaultInstance;
    public static ListMoneyHistoryRsp getDefaultInstance() {
      return defaultInstance;
    }

    public ListMoneyHistoryRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ListMoneyHistoryRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                history_ = new java.util.ArrayList<com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg>();
                mutable_bitField0_ |= 0x00000001;
              }
              history_.add(input.readMessage(com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          history_ = java.util.Collections.unmodifiableList(history_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zc.web.message.player.ListMoneyHistoryRspProto.internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zc.web.message.player.ListMoneyHistoryRspProto.internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.class, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<ListMoneyHistoryRsp> PARSER =
        new com.google.protobuf.AbstractParser<ListMoneyHistoryRsp>() {
      public ListMoneyHistoryRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListMoneyHistoryRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ListMoneyHistoryRsp> getParserForType() {
      return PARSER;
    }

    public interface MoneyHistoryMsgOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional int64 id = 1;
      /**
       * <code>optional int64 id = 1;</code>
       *
       * <pre>
       * id
       * </pre>
       */
      boolean hasId();
      /**
       * <code>optional int64 id = 1;</code>
       *
       * <pre>
       * id
       * </pre>
       */
      long getId();

      // optional int32 money = 2;
      /**
       * <code>optional int32 money = 2;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      boolean hasMoney();
      /**
       * <code>optional int32 money = 2;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      int getMoney();

      // optional int32 type = 3;
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 0：系统；1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
       * </pre>
       */
      boolean hasType();
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 0：系统；1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
       * </pre>
       */
      int getType();

      // optional int32 platform = 4;
      /**
       * <code>optional int32 platform = 4;</code>
       *
       * <pre>
       * 0：默认；1：银联
       * </pre>
       */
      boolean hasPlatform();
      /**
       * <code>optional int32 platform = 4;</code>
       *
       * <pre>
       * 0：默认；1：银联
       * </pre>
       */
      int getPlatform();

      // optional int32 time = 5;
      /**
       * <code>optional int32 time = 5;</code>
       *
       * <pre>
       * 操作时间
       * </pre>
       */
      boolean hasTime();
      /**
       * <code>optional int32 time = 5;</code>
       *
       * <pre>
       * 操作时间
       * </pre>
       */
      int getTime();

      // optional int32 state = 6;
      /**
       * <code>optional int32 state = 6;</code>
       *
       * <pre>
       * 0：失败；1：成功
       * </pre>
       */
      boolean hasState();
      /**
       * <code>optional int32 state = 6;</code>
       *
       * <pre>
       * 0：失败；1：成功
       * </pre>
       */
      int getState();

      // optional int32 balance = 8;
      /**
       * <code>optional int32 balance = 8;</code>
       *
       * <pre>
       * 余额
       * </pre>
       */
      boolean hasBalance();
      /**
       * <code>optional int32 balance = 8;</code>
       *
       * <pre>
       * 余额
       * </pre>
       */
      int getBalance();

      // optional string descript = 7;
      /**
       * <code>optional string descript = 7;</code>
       *
       * <pre>
       * 备注
       * </pre>
       */
      boolean hasDescript();
      /**
       * <code>optional string descript = 7;</code>
       *
       * <pre>
       * 备注
       * </pre>
       */
      java.lang.String getDescript();
      /**
       * <code>optional string descript = 7;</code>
       *
       * <pre>
       * 备注
       * </pre>
       */
      com.google.protobuf.ByteString
          getDescriptBytes();
    }
    /**
     * Protobuf type {@code com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg}
     */
    public static final class MoneyHistoryMsg extends
        com.google.protobuf.GeneratedMessage
        implements MoneyHistoryMsgOrBuilder {
      // Use MoneyHistoryMsg.newBuilder() to construct.
      private MoneyHistoryMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private MoneyHistoryMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final MoneyHistoryMsg defaultInstance;
      public static MoneyHistoryMsg getDefaultInstance() {
        return defaultInstance;
      }

      public MoneyHistoryMsg getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private MoneyHistoryMsg(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                id_ = input.readInt64();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                money_ = input.readInt32();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                type_ = input.readInt32();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                platform_ = input.readInt32();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                time_ = input.readInt32();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                state_ = input.readInt32();
                break;
              }
              case 58: {
                bitField0_ |= 0x00000080;
                descript_ = input.readBytes();
                break;
              }
              case 64: {
                bitField0_ |= 0x00000040;
                balance_ = input.readInt32();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zc.web.message.player.ListMoneyHistoryRspProto.internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_MoneyHistoryMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zc.web.message.player.ListMoneyHistoryRspProto.internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_MoneyHistoryMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.class, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder.class);
      }

      public static com.google.protobuf.Parser<MoneyHistoryMsg> PARSER =
          new com.google.protobuf.AbstractParser<MoneyHistoryMsg>() {
        public MoneyHistoryMsg parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new MoneyHistoryMsg(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<MoneyHistoryMsg> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional int64 id = 1;
      public static final int ID_FIELD_NUMBER = 1;
      private long id_;
      /**
       * <code>optional int64 id = 1;</code>
       *
       * <pre>
       * id
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 id = 1;</code>
       *
       * <pre>
       * id
       * </pre>
       */
      public long getId() {
        return id_;
      }

      // optional int32 money = 2;
      public static final int MONEY_FIELD_NUMBER = 2;
      private int money_;
      /**
       * <code>optional int32 money = 2;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      public boolean hasMoney() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 money = 2;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      public int getMoney() {
        return money_;
      }

      // optional int32 type = 3;
      public static final int TYPE_FIELD_NUMBER = 3;
      private int type_;
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 0：系统；1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 0：系统；1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
       * </pre>
       */
      public int getType() {
        return type_;
      }

      // optional int32 platform = 4;
      public static final int PLATFORM_FIELD_NUMBER = 4;
      private int platform_;
      /**
       * <code>optional int32 platform = 4;</code>
       *
       * <pre>
       * 0：默认；1：银联
       * </pre>
       */
      public boolean hasPlatform() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 platform = 4;</code>
       *
       * <pre>
       * 0：默认；1：银联
       * </pre>
       */
      public int getPlatform() {
        return platform_;
      }

      // optional int32 time = 5;
      public static final int TIME_FIELD_NUMBER = 5;
      private int time_;
      /**
       * <code>optional int32 time = 5;</code>
       *
       * <pre>
       * 操作时间
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 time = 5;</code>
       *
       * <pre>
       * 操作时间
       * </pre>
       */
      public int getTime() {
        return time_;
      }

      // optional int32 state = 6;
      public static final int STATE_FIELD_NUMBER = 6;
      private int state_;
      /**
       * <code>optional int32 state = 6;</code>
       *
       * <pre>
       * 0：失败；1：成功
       * </pre>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 state = 6;</code>
       *
       * <pre>
       * 0：失败；1：成功
       * </pre>
       */
      public int getState() {
        return state_;
      }

      // optional int32 balance = 8;
      public static final int BALANCE_FIELD_NUMBER = 8;
      private int balance_;
      /**
       * <code>optional int32 balance = 8;</code>
       *
       * <pre>
       * 余额
       * </pre>
       */
      public boolean hasBalance() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional int32 balance = 8;</code>
       *
       * <pre>
       * 余额
       * </pre>
       */
      public int getBalance() {
        return balance_;
      }

      // optional string descript = 7;
      public static final int DESCRIPT_FIELD_NUMBER = 7;
      private java.lang.Object descript_;
      /**
       * <code>optional string descript = 7;</code>
       *
       * <pre>
       * 备注
       * </pre>
       */
      public boolean hasDescript() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional string descript = 7;</code>
       *
       * <pre>
       * 备注
       * </pre>
       */
      public java.lang.String getDescript() {
        java.lang.Object ref = descript_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            descript_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string descript = 7;</code>
       *
       * <pre>
       * 备注
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDescriptBytes() {
        java.lang.Object ref = descript_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          descript_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        id_ = 0L;
        money_ = 0;
        type_ = 0;
        platform_ = 0;
        time_ = 0;
        state_ = 0;
        balance_ = 0;
        descript_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt32(2, money_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt32(3, type_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, platform_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeInt32(5, time_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeInt32(6, state_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeBytes(7, getDescriptBytes());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeInt32(8, balance_);
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, id_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(2, money_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(3, type_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, platform_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, time_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, state_);
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(7, getDescriptBytes());
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(8, balance_);
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsgOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.zc.web.message.player.ListMoneyHistoryRspProto.internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_MoneyHistoryMsg_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.zc.web.message.player.ListMoneyHistoryRspProto.internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_MoneyHistoryMsg_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.class, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder.class);
        }

        // Construct using com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          id_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          money_ = 0;
          bitField0_ = (bitField0_ & ~0x00000002);
          type_ = 0;
          bitField0_ = (bitField0_ & ~0x00000004);
          platform_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          time_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          state_ = 0;
          bitField0_ = (bitField0_ & ~0x00000020);
          balance_ = 0;
          bitField0_ = (bitField0_ & ~0x00000040);
          descript_ = "";
          bitField0_ = (bitField0_ & ~0x00000080);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.zc.web.message.player.ListMoneyHistoryRspProto.internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_MoneyHistoryMsg_descriptor;
        }

        public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg getDefaultInstanceForType() {
          return com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.getDefaultInstance();
        }

        public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg build() {
          com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg buildPartial() {
          com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg result = new com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.id_ = id_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.money_ = money_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.type_ = type_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.platform_ = platform_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.time_ = time_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.state_ = state_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.balance_ = balance_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000080;
          }
          result.descript_ = descript_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg) {
            return mergeFrom((com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg other) {
          if (other == com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.getDefaultInstance()) return this;
          if (other.hasId()) {
            setId(other.getId());
          }
          if (other.hasMoney()) {
            setMoney(other.getMoney());
          }
          if (other.hasType()) {
            setType(other.getType());
          }
          if (other.hasPlatform()) {
            setPlatform(other.getPlatform());
          }
          if (other.hasTime()) {
            setTime(other.getTime());
          }
          if (other.hasState()) {
            setState(other.getState());
          }
          if (other.hasBalance()) {
            setBalance(other.getBalance());
          }
          if (other.hasDescript()) {
            bitField0_ |= 0x00000080;
            descript_ = other.descript_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional int64 id = 1;
        private long id_ ;
        /**
         * <code>optional int64 id = 1;</code>
         *
         * <pre>
         * id
         * </pre>
         */
        public boolean hasId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int64 id = 1;</code>
         *
         * <pre>
         * id
         * </pre>
         */
        public long getId() {
          return id_;
        }
        /**
         * <code>optional int64 id = 1;</code>
         *
         * <pre>
         * id
         * </pre>
         */
        public Builder setId(long value) {
          bitField0_ |= 0x00000001;
          id_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 id = 1;</code>
         *
         * <pre>
         * id
         * </pre>
         */
        public Builder clearId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          id_ = 0L;
          onChanged();
          return this;
        }

        // optional int32 money = 2;
        private int money_ ;
        /**
         * <code>optional int32 money = 2;</code>
         *
         * <pre>
         * 金额
         * </pre>
         */
        public boolean hasMoney() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int32 money = 2;</code>
         *
         * <pre>
         * 金额
         * </pre>
         */
        public int getMoney() {
          return money_;
        }
        /**
         * <code>optional int32 money = 2;</code>
         *
         * <pre>
         * 金额
         * </pre>
         */
        public Builder setMoney(int value) {
          bitField0_ |= 0x00000002;
          money_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 money = 2;</code>
         *
         * <pre>
         * 金额
         * </pre>
         */
        public Builder clearMoney() {
          bitField0_ = (bitField0_ & ~0x00000002);
          money_ = 0;
          onChanged();
          return this;
        }

        // optional int32 type = 3;
        private int type_ ;
        /**
         * <code>optional int32 type = 3;</code>
         *
         * <pre>
         * 0：系统；1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
         * </pre>
         */
        public boolean hasType() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int32 type = 3;</code>
         *
         * <pre>
         * 0：系统；1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
         * </pre>
         */
        public int getType() {
          return type_;
        }
        /**
         * <code>optional int32 type = 3;</code>
         *
         * <pre>
         * 0：系统；1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
         * </pre>
         */
        public Builder setType(int value) {
          bitField0_ |= 0x00000004;
          type_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 type = 3;</code>
         *
         * <pre>
         * 0：系统；1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
         * </pre>
         */
        public Builder clearType() {
          bitField0_ = (bitField0_ & ~0x00000004);
          type_ = 0;
          onChanged();
          return this;
        }

        // optional int32 platform = 4;
        private int platform_ ;
        /**
         * <code>optional int32 platform = 4;</code>
         *
         * <pre>
         * 0：默认；1：银联
         * </pre>
         */
        public boolean hasPlatform() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int32 platform = 4;</code>
         *
         * <pre>
         * 0：默认；1：银联
         * </pre>
         */
        public int getPlatform() {
          return platform_;
        }
        /**
         * <code>optional int32 platform = 4;</code>
         *
         * <pre>
         * 0：默认；1：银联
         * </pre>
         */
        public Builder setPlatform(int value) {
          bitField0_ |= 0x00000008;
          platform_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 platform = 4;</code>
         *
         * <pre>
         * 0：默认；1：银联
         * </pre>
         */
        public Builder clearPlatform() {
          bitField0_ = (bitField0_ & ~0x00000008);
          platform_ = 0;
          onChanged();
          return this;
        }

        // optional int32 time = 5;
        private int time_ ;
        /**
         * <code>optional int32 time = 5;</code>
         *
         * <pre>
         * 操作时间
         * </pre>
         */
        public boolean hasTime() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional int32 time = 5;</code>
         *
         * <pre>
         * 操作时间
         * </pre>
         */
        public int getTime() {
          return time_;
        }
        /**
         * <code>optional int32 time = 5;</code>
         *
         * <pre>
         * 操作时间
         * </pre>
         */
        public Builder setTime(int value) {
          bitField0_ |= 0x00000010;
          time_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 time = 5;</code>
         *
         * <pre>
         * 操作时间
         * </pre>
         */
        public Builder clearTime() {
          bitField0_ = (bitField0_ & ~0x00000010);
          time_ = 0;
          onChanged();
          return this;
        }

        // optional int32 state = 6;
        private int state_ ;
        /**
         * <code>optional int32 state = 6;</code>
         *
         * <pre>
         * 0：失败；1：成功
         * </pre>
         */
        public boolean hasState() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional int32 state = 6;</code>
         *
         * <pre>
         * 0：失败；1：成功
         * </pre>
         */
        public int getState() {
          return state_;
        }
        /**
         * <code>optional int32 state = 6;</code>
         *
         * <pre>
         * 0：失败；1：成功
         * </pre>
         */
        public Builder setState(int value) {
          bitField0_ |= 0x00000020;
          state_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 state = 6;</code>
         *
         * <pre>
         * 0：失败；1：成功
         * </pre>
         */
        public Builder clearState() {
          bitField0_ = (bitField0_ & ~0x00000020);
          state_ = 0;
          onChanged();
          return this;
        }

        // optional int32 balance = 8;
        private int balance_ ;
        /**
         * <code>optional int32 balance = 8;</code>
         *
         * <pre>
         * 余额
         * </pre>
         */
        public boolean hasBalance() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional int32 balance = 8;</code>
         *
         * <pre>
         * 余额
         * </pre>
         */
        public int getBalance() {
          return balance_;
        }
        /**
         * <code>optional int32 balance = 8;</code>
         *
         * <pre>
         * 余额
         * </pre>
         */
        public Builder setBalance(int value) {
          bitField0_ |= 0x00000040;
          balance_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 balance = 8;</code>
         *
         * <pre>
         * 余额
         * </pre>
         */
        public Builder clearBalance() {
          bitField0_ = (bitField0_ & ~0x00000040);
          balance_ = 0;
          onChanged();
          return this;
        }

        // optional string descript = 7;
        private java.lang.Object descript_ = "";
        /**
         * <code>optional string descript = 7;</code>
         *
         * <pre>
         * 备注
         * </pre>
         */
        public boolean hasDescript() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>optional string descript = 7;</code>
         *
         * <pre>
         * 备注
         * </pre>
         */
        public java.lang.String getDescript() {
          java.lang.Object ref = descript_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            descript_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string descript = 7;</code>
         *
         * <pre>
         * 备注
         * </pre>
         */
        public com.google.protobuf.ByteString
            getDescriptBytes() {
          java.lang.Object ref = descript_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            descript_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string descript = 7;</code>
         *
         * <pre>
         * 备注
         * </pre>
         */
        public Builder setDescript(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
          descript_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string descript = 7;</code>
         *
         * <pre>
         * 备注
         * </pre>
         */
        public Builder clearDescript() {
          bitField0_ = (bitField0_ & ~0x00000080);
          descript_ = getDefaultInstance().getDescript();
          onChanged();
          return this;
        }
        /**
         * <code>optional string descript = 7;</code>
         *
         * <pre>
         * 备注
         * </pre>
         */
        public Builder setDescriptBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
          descript_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg)
      }

      static {
        defaultInstance = new MoneyHistoryMsg(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg)
    }

    // repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;
    public static final int HISTORY_FIELD_NUMBER = 1;
    private java.util.List<com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg> history_;
    /**
     * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
     */
    public java.util.List<com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg> getHistoryList() {
      return history_;
    }
    /**
     * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
     */
    public java.util.List<? extends com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsgOrBuilder> 
        getHistoryOrBuilderList() {
      return history_;
    }
    /**
     * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
     */
    public int getHistoryCount() {
      return history_.size();
    }
    /**
     * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
     */
    public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg getHistory(int index) {
      return history_.get(index);
    }
    /**
     * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
     */
    public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsgOrBuilder getHistoryOrBuilder(
        int index) {
      return history_.get(index);
    }

    private void initFields() {
      history_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < history_.size(); i++) {
        output.writeMessage(1, history_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < history_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, history_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zc.web.message.player.ListMoneyHistoryRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zc.web.message.player.ListMoneyHistoryRspProto.internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zc.web.message.player.ListMoneyHistoryRspProto.internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.class, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.Builder.class);
      }

      // Construct using com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getHistoryFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (historyBuilder_ == null) {
          history_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          historyBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zc.web.message.player.ListMoneyHistoryRspProto.internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_descriptor;
      }

      public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp getDefaultInstanceForType() {
        return com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.getDefaultInstance();
      }

      public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp build() {
        com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp buildPartial() {
        com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp result = new com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp(this);
        int from_bitField0_ = bitField0_;
        if (historyBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            history_ = java.util.Collections.unmodifiableList(history_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.history_ = history_;
        } else {
          result.history_ = historyBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp) {
          return mergeFrom((com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp other) {
        if (other == com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.getDefaultInstance()) return this;
        if (historyBuilder_ == null) {
          if (!other.history_.isEmpty()) {
            if (history_.isEmpty()) {
              history_ = other.history_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureHistoryIsMutable();
              history_.addAll(other.history_);
            }
            onChanged();
          }
        } else {
          if (!other.history_.isEmpty()) {
            if (historyBuilder_.isEmpty()) {
              historyBuilder_.dispose();
              historyBuilder_ = null;
              history_ = other.history_;
              bitField0_ = (bitField0_ & ~0x00000001);
              historyBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getHistoryFieldBuilder() : null;
            } else {
              historyBuilder_.addAllMessages(other.history_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;
      private java.util.List<com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg> history_ =
        java.util.Collections.emptyList();
      private void ensureHistoryIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          history_ = new java.util.ArrayList<com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg>(history_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsgOrBuilder> historyBuilder_;

      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public java.util.List<com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg> getHistoryList() {
        if (historyBuilder_ == null) {
          return java.util.Collections.unmodifiableList(history_);
        } else {
          return historyBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public int getHistoryCount() {
        if (historyBuilder_ == null) {
          return history_.size();
        } else {
          return historyBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg getHistory(int index) {
        if (historyBuilder_ == null) {
          return history_.get(index);
        } else {
          return historyBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public Builder setHistory(
          int index, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg value) {
        if (historyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHistoryIsMutable();
          history_.set(index, value);
          onChanged();
        } else {
          historyBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public Builder setHistory(
          int index, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder builderForValue) {
        if (historyBuilder_ == null) {
          ensureHistoryIsMutable();
          history_.set(index, builderForValue.build());
          onChanged();
        } else {
          historyBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public Builder addHistory(com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg value) {
        if (historyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHistoryIsMutable();
          history_.add(value);
          onChanged();
        } else {
          historyBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public Builder addHistory(
          int index, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg value) {
        if (historyBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureHistoryIsMutable();
          history_.add(index, value);
          onChanged();
        } else {
          historyBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public Builder addHistory(
          com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder builderForValue) {
        if (historyBuilder_ == null) {
          ensureHistoryIsMutable();
          history_.add(builderForValue.build());
          onChanged();
        } else {
          historyBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public Builder addHistory(
          int index, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder builderForValue) {
        if (historyBuilder_ == null) {
          ensureHistoryIsMutable();
          history_.add(index, builderForValue.build());
          onChanged();
        } else {
          historyBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public Builder addAllHistory(
          java.lang.Iterable<? extends com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg> values) {
        if (historyBuilder_ == null) {
          ensureHistoryIsMutable();
          super.addAll(values, history_);
          onChanged();
        } else {
          historyBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public Builder clearHistory() {
        if (historyBuilder_ == null) {
          history_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          historyBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public Builder removeHistory(int index) {
        if (historyBuilder_ == null) {
          ensureHistoryIsMutable();
          history_.remove(index);
          onChanged();
        } else {
          historyBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder getHistoryBuilder(
          int index) {
        return getHistoryFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsgOrBuilder getHistoryOrBuilder(
          int index) {
        if (historyBuilder_ == null) {
          return history_.get(index);  } else {
          return historyBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public java.util.List<? extends com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsgOrBuilder> 
           getHistoryOrBuilderList() {
        if (historyBuilder_ != null) {
          return historyBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(history_);
        }
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder addHistoryBuilder() {
        return getHistoryFieldBuilder().addBuilder(
            com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder addHistoryBuilder(
          int index) {
        return getHistoryFieldBuilder().addBuilder(
            index, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zc.web.message.player.ListMoneyHistoryRsp.MoneyHistoryMsg history = 1;</code>
       */
      public java.util.List<com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder> 
           getHistoryBuilderList() {
        return getHistoryFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsgOrBuilder> 
          getHistoryFieldBuilder() {
        if (historyBuilder_ == null) {
          historyBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsg.Builder, com.zc.web.message.player.ListMoneyHistoryRspProto.ListMoneyHistoryRsp.MoneyHistoryMsgOrBuilder>(
                  history_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          history_ = null;
        }
        return historyBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.zc.web.message.player.ListMoneyHistoryRsp)
    }

    static {
      defaultInstance = new ListMoneyHistoryRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zc.web.message.player.ListMoneyHistoryRsp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_MoneyHistoryMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_MoneyHistoryMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?main/resources/com/zc/messages/player/" +
      "ListMoneyHistoryRsp.proto\022\031com.zc.web.me" +
      "ssage.player\"\365\001\n\023ListMoneyHistoryRsp\022O\n\007" +
      "history\030\001 \003(\0132>.com.zc.web.message.playe" +
      "r.ListMoneyHistoryRsp.MoneyHistoryMsg\032\214\001" +
      "\n\017MoneyHistoryMsg\022\n\n\002id\030\001 \001(\003\022\r\n\005money\030\002" +
      " \001(\005\022\014\n\004type\030\003 \001(\005\022\020\n\010platform\030\004 \001(\005\022\014\n\004" +
      "time\030\005 \001(\005\022\r\n\005state\030\006 \001(\005\022\017\n\007balance\030\010 \001" +
      "(\005\022\020\n\010descript\030\007 \001(\tB\032B\030ListMoneyHistory" +
      "RspProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_descriptor,
              new java.lang.String[] { "History", });
          internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_MoneyHistoryMsg_descriptor =
            internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_descriptor.getNestedTypes().get(0);
          internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_MoneyHistoryMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zc_web_message_player_ListMoneyHistoryRsp_MoneyHistoryMsg_descriptor,
              new java.lang.String[] { "Id", "Money", "Type", "Platform", "Time", "State", "Balance", "Descript", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
