// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/com/zc/messages/debt/ListRepayReq.proto

package com.zc.web.message.debt;

public final class ListRepayReqProto {
  private ListRepayReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ListRepayReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 page = 1;
    /**
     * <code>optional int32 page = 1;</code>
     *
     * <pre>
     * 第n页
     * </pre>
     */
    boolean hasPage();
    /**
     * <code>optional int32 page = 1;</code>
     *
     * <pre>
     * 第n页
     * </pre>
     */
    int getPage();

    // optional string debtId = 2;
    /**
     * <code>optional string debtId = 2;</code>
     *
     * <pre>
     * 债务id
     * </pre>
     */
    boolean hasDebtId();
    /**
     * <code>optional string debtId = 2;</code>
     *
     * <pre>
     * 债务id
     * </pre>
     */
    java.lang.String getDebtId();
    /**
     * <code>optional string debtId = 2;</code>
     *
     * <pre>
     * 债务id
     * </pre>
     */
    com.google.protobuf.ByteString
        getDebtIdBytes();

    // optional string ownerId = 3;
    /**
     * <code>optional string ownerId = 3;</code>
     *
     * <pre>
     * 发布人ID
     * </pre>
     */
    boolean hasOwnerId();
    /**
     * <code>optional string ownerId = 3;</code>
     *
     * <pre>
     * 发布人ID
     * </pre>
     */
    java.lang.String getOwnerId();
    /**
     * <code>optional string ownerId = 3;</code>
     *
     * <pre>
     * 发布人ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getOwnerIdBytes();

    // optional string deputyId = 4;
    /**
     * <code>optional string deputyId = 4;</code>
     *
     * <pre>
     * 代理人ID
     * </pre>
     */
    boolean hasDeputyId();
    /**
     * <code>optional string deputyId = 4;</code>
     *
     * <pre>
     * 代理人ID
     * </pre>
     */
    java.lang.String getDeputyId();
    /**
     * <code>optional string deputyId = 4;</code>
     *
     * <pre>
     * 代理人ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getDeputyIdBytes();

    // optional int32 timeFrom = 5;
    /**
     * <code>optional int32 timeFrom = 5;</code>
     *
     * <pre>
     * 时间（起）
     * </pre>
     */
    boolean hasTimeFrom();
    /**
     * <code>optional int32 timeFrom = 5;</code>
     *
     * <pre>
     * 时间（起）
     * </pre>
     */
    int getTimeFrom();

    // optional int32 timeTo = 6;
    /**
     * <code>optional int32 timeTo = 6;</code>
     *
     * <pre>
     * 时间（止）
     * </pre>
     */
    boolean hasTimeTo();
    /**
     * <code>optional int32 timeTo = 6;</code>
     *
     * <pre>
     * 时间（止）
     * </pre>
     */
    int getTimeTo();
  }
  /**
   * Protobuf type {@code com.zc.web.message.debt.ListRepayReq}
   */
  public static final class ListRepayReq extends
      com.google.protobuf.GeneratedMessage
      implements ListRepayReqOrBuilder {
    // Use ListRepayReq.newBuilder() to construct.
    private ListRepayReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ListRepayReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ListRepayReq defaultInstance;
    public static ListRepayReq getDefaultInstance() {
      return defaultInstance;
    }

    public ListRepayReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ListRepayReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              page_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              debtId_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              ownerId_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              deputyId_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              timeFrom_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              timeTo_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zc.web.message.debt.ListRepayReqProto.internal_static_com_zc_web_message_debt_ListRepayReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zc.web.message.debt.ListRepayReqProto.internal_static_com_zc_web_message_debt_ListRepayReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zc.web.message.debt.ListRepayReqProto.ListRepayReq.class, com.zc.web.message.debt.ListRepayReqProto.ListRepayReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ListRepayReq> PARSER =
        new com.google.protobuf.AbstractParser<ListRepayReq>() {
      public ListRepayReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListRepayReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ListRepayReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 page = 1;
    public static final int PAGE_FIELD_NUMBER = 1;
    private int page_;
    /**
     * <code>optional int32 page = 1;</code>
     *
     * <pre>
     * 第n页
     * </pre>
     */
    public boolean hasPage() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 page = 1;</code>
     *
     * <pre>
     * 第n页
     * </pre>
     */
    public int getPage() {
      return page_;
    }

    // optional string debtId = 2;
    public static final int DEBTID_FIELD_NUMBER = 2;
    private java.lang.Object debtId_;
    /**
     * <code>optional string debtId = 2;</code>
     *
     * <pre>
     * 债务id
     * </pre>
     */
    public boolean hasDebtId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional string debtId = 2;</code>
     *
     * <pre>
     * 债务id
     * </pre>
     */
    public java.lang.String getDebtId() {
      java.lang.Object ref = debtId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          debtId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string debtId = 2;</code>
     *
     * <pre>
     * 债务id
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDebtIdBytes() {
      java.lang.Object ref = debtId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        debtId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string ownerId = 3;
    public static final int OWNERID_FIELD_NUMBER = 3;
    private java.lang.Object ownerId_;
    /**
     * <code>optional string ownerId = 3;</code>
     *
     * <pre>
     * 发布人ID
     * </pre>
     */
    public boolean hasOwnerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string ownerId = 3;</code>
     *
     * <pre>
     * 发布人ID
     * </pre>
     */
    public java.lang.String getOwnerId() {
      java.lang.Object ref = ownerId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          ownerId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string ownerId = 3;</code>
     *
     * <pre>
     * 发布人ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getOwnerIdBytes() {
      java.lang.Object ref = ownerId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ownerId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string deputyId = 4;
    public static final int DEPUTYID_FIELD_NUMBER = 4;
    private java.lang.Object deputyId_;
    /**
     * <code>optional string deputyId = 4;</code>
     *
     * <pre>
     * 代理人ID
     * </pre>
     */
    public boolean hasDeputyId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string deputyId = 4;</code>
     *
     * <pre>
     * 代理人ID
     * </pre>
     */
    public java.lang.String getDeputyId() {
      java.lang.Object ref = deputyId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          deputyId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string deputyId = 4;</code>
     *
     * <pre>
     * 代理人ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getDeputyIdBytes() {
      java.lang.Object ref = deputyId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        deputyId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 timeFrom = 5;
    public static final int TIMEFROM_FIELD_NUMBER = 5;
    private int timeFrom_;
    /**
     * <code>optional int32 timeFrom = 5;</code>
     *
     * <pre>
     * 时间（起）
     * </pre>
     */
    public boolean hasTimeFrom() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 timeFrom = 5;</code>
     *
     * <pre>
     * 时间（起）
     * </pre>
     */
    public int getTimeFrom() {
      return timeFrom_;
    }

    // optional int32 timeTo = 6;
    public static final int TIMETO_FIELD_NUMBER = 6;
    private int timeTo_;
    /**
     * <code>optional int32 timeTo = 6;</code>
     *
     * <pre>
     * 时间（止）
     * </pre>
     */
    public boolean hasTimeTo() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional int32 timeTo = 6;</code>
     *
     * <pre>
     * 时间（止）
     * </pre>
     */
    public int getTimeTo() {
      return timeTo_;
    }

    private void initFields() {
      page_ = 0;
      debtId_ = "";
      ownerId_ = "";
      deputyId_ = "";
      timeFrom_ = 0;
      timeTo_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, page_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getDebtIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getOwnerIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getDeputyIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, timeFrom_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt32(6, timeTo_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, page_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getDebtIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getOwnerIdBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getDeputyIdBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, timeFrom_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, timeTo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zc.web.message.debt.ListRepayReqProto.ListRepayReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zc.web.message.debt.ListRepayReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zc.web.message.debt.ListRepayReqProto.ListRepayReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zc.web.message.debt.ListRepayReqProto.internal_static_com_zc_web_message_debt_ListRepayReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zc.web.message.debt.ListRepayReqProto.internal_static_com_zc_web_message_debt_ListRepayReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zc.web.message.debt.ListRepayReqProto.ListRepayReq.class, com.zc.web.message.debt.ListRepayReqProto.ListRepayReq.Builder.class);
      }

      // Construct using com.zc.web.message.debt.ListRepayReqProto.ListRepayReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        page_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        debtId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        ownerId_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        deputyId_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        timeFrom_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        timeTo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zc.web.message.debt.ListRepayReqProto.internal_static_com_zc_web_message_debt_ListRepayReq_descriptor;
      }

      public com.zc.web.message.debt.ListRepayReqProto.ListRepayReq getDefaultInstanceForType() {
        return com.zc.web.message.debt.ListRepayReqProto.ListRepayReq.getDefaultInstance();
      }

      public com.zc.web.message.debt.ListRepayReqProto.ListRepayReq build() {
        com.zc.web.message.debt.ListRepayReqProto.ListRepayReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zc.web.message.debt.ListRepayReqProto.ListRepayReq buildPartial() {
        com.zc.web.message.debt.ListRepayReqProto.ListRepayReq result = new com.zc.web.message.debt.ListRepayReqProto.ListRepayReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.page_ = page_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.debtId_ = debtId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.ownerId_ = ownerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.deputyId_ = deputyId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.timeFrom_ = timeFrom_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timeTo_ = timeTo_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zc.web.message.debt.ListRepayReqProto.ListRepayReq) {
          return mergeFrom((com.zc.web.message.debt.ListRepayReqProto.ListRepayReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zc.web.message.debt.ListRepayReqProto.ListRepayReq other) {
        if (other == com.zc.web.message.debt.ListRepayReqProto.ListRepayReq.getDefaultInstance()) return this;
        if (other.hasPage()) {
          setPage(other.getPage());
        }
        if (other.hasDebtId()) {
          bitField0_ |= 0x00000002;
          debtId_ = other.debtId_;
          onChanged();
        }
        if (other.hasOwnerId()) {
          bitField0_ |= 0x00000004;
          ownerId_ = other.ownerId_;
          onChanged();
        }
        if (other.hasDeputyId()) {
          bitField0_ |= 0x00000008;
          deputyId_ = other.deputyId_;
          onChanged();
        }
        if (other.hasTimeFrom()) {
          setTimeFrom(other.getTimeFrom());
        }
        if (other.hasTimeTo()) {
          setTimeTo(other.getTimeTo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zc.web.message.debt.ListRepayReqProto.ListRepayReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zc.web.message.debt.ListRepayReqProto.ListRepayReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 page = 1;
      private int page_ ;
      /**
       * <code>optional int32 page = 1;</code>
       *
       * <pre>
       * 第n页
       * </pre>
       */
      public boolean hasPage() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 page = 1;</code>
       *
       * <pre>
       * 第n页
       * </pre>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>optional int32 page = 1;</code>
       *
       * <pre>
       * 第n页
       * </pre>
       */
      public Builder setPage(int value) {
        bitField0_ |= 0x00000001;
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 page = 1;</code>
       *
       * <pre>
       * 第n页
       * </pre>
       */
      public Builder clearPage() {
        bitField0_ = (bitField0_ & ~0x00000001);
        page_ = 0;
        onChanged();
        return this;
      }

      // optional string debtId = 2;
      private java.lang.Object debtId_ = "";
      /**
       * <code>optional string debtId = 2;</code>
       *
       * <pre>
       * 债务id
       * </pre>
       */
      public boolean hasDebtId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string debtId = 2;</code>
       *
       * <pre>
       * 债务id
       * </pre>
       */
      public java.lang.String getDebtId() {
        java.lang.Object ref = debtId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          debtId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string debtId = 2;</code>
       *
       * <pre>
       * 债务id
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDebtIdBytes() {
        java.lang.Object ref = debtId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          debtId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string debtId = 2;</code>
       *
       * <pre>
       * 债务id
       * </pre>
       */
      public Builder setDebtId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        debtId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string debtId = 2;</code>
       *
       * <pre>
       * 债务id
       * </pre>
       */
      public Builder clearDebtId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        debtId_ = getDefaultInstance().getDebtId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string debtId = 2;</code>
       *
       * <pre>
       * 债务id
       * </pre>
       */
      public Builder setDebtIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        debtId_ = value;
        onChanged();
        return this;
      }

      // optional string ownerId = 3;
      private java.lang.Object ownerId_ = "";
      /**
       * <code>optional string ownerId = 3;</code>
       *
       * <pre>
       * 发布人ID
       * </pre>
       */
      public boolean hasOwnerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string ownerId = 3;</code>
       *
       * <pre>
       * 发布人ID
       * </pre>
       */
      public java.lang.String getOwnerId() {
        java.lang.Object ref = ownerId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          ownerId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string ownerId = 3;</code>
       *
       * <pre>
       * 发布人ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getOwnerIdBytes() {
        java.lang.Object ref = ownerId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ownerId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string ownerId = 3;</code>
       *
       * <pre>
       * 发布人ID
       * </pre>
       */
      public Builder setOwnerId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ownerId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string ownerId = 3;</code>
       *
       * <pre>
       * 发布人ID
       * </pre>
       */
      public Builder clearOwnerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        ownerId_ = getDefaultInstance().getOwnerId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string ownerId = 3;</code>
       *
       * <pre>
       * 发布人ID
       * </pre>
       */
      public Builder setOwnerIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        ownerId_ = value;
        onChanged();
        return this;
      }

      // optional string deputyId = 4;
      private java.lang.Object deputyId_ = "";
      /**
       * <code>optional string deputyId = 4;</code>
       *
       * <pre>
       * 代理人ID
       * </pre>
       */
      public boolean hasDeputyId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string deputyId = 4;</code>
       *
       * <pre>
       * 代理人ID
       * </pre>
       */
      public java.lang.String getDeputyId() {
        java.lang.Object ref = deputyId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          deputyId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string deputyId = 4;</code>
       *
       * <pre>
       * 代理人ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getDeputyIdBytes() {
        java.lang.Object ref = deputyId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          deputyId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string deputyId = 4;</code>
       *
       * <pre>
       * 代理人ID
       * </pre>
       */
      public Builder setDeputyId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deputyId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string deputyId = 4;</code>
       *
       * <pre>
       * 代理人ID
       * </pre>
       */
      public Builder clearDeputyId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        deputyId_ = getDefaultInstance().getDeputyId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string deputyId = 4;</code>
       *
       * <pre>
       * 代理人ID
       * </pre>
       */
      public Builder setDeputyIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        deputyId_ = value;
        onChanged();
        return this;
      }

      // optional int32 timeFrom = 5;
      private int timeFrom_ ;
      /**
       * <code>optional int32 timeFrom = 5;</code>
       *
       * <pre>
       * 时间（起）
       * </pre>
       */
      public boolean hasTimeFrom() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 timeFrom = 5;</code>
       *
       * <pre>
       * 时间（起）
       * </pre>
       */
      public int getTimeFrom() {
        return timeFrom_;
      }
      /**
       * <code>optional int32 timeFrom = 5;</code>
       *
       * <pre>
       * 时间（起）
       * </pre>
       */
      public Builder setTimeFrom(int value) {
        bitField0_ |= 0x00000010;
        timeFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 timeFrom = 5;</code>
       *
       * <pre>
       * 时间（起）
       * </pre>
       */
      public Builder clearTimeFrom() {
        bitField0_ = (bitField0_ & ~0x00000010);
        timeFrom_ = 0;
        onChanged();
        return this;
      }

      // optional int32 timeTo = 6;
      private int timeTo_ ;
      /**
       * <code>optional int32 timeTo = 6;</code>
       *
       * <pre>
       * 时间（止）
       * </pre>
       */
      public boolean hasTimeTo() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 timeTo = 6;</code>
       *
       * <pre>
       * 时间（止）
       * </pre>
       */
      public int getTimeTo() {
        return timeTo_;
      }
      /**
       * <code>optional int32 timeTo = 6;</code>
       *
       * <pre>
       * 时间（止）
       * </pre>
       */
      public Builder setTimeTo(int value) {
        bitField0_ |= 0x00000020;
        timeTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 timeTo = 6;</code>
       *
       * <pre>
       * 时间（止）
       * </pre>
       */
      public Builder clearTimeTo() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timeTo_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zc.web.message.debt.ListRepayReq)
    }

    static {
      defaultInstance = new ListRepayReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zc.web.message.debt.ListRepayReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zc_web_message_debt_ListRepayReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zc_web_message_debt_ListRepayReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6main/resources/com/zc/messages/debt/Li" +
      "stRepayReq.proto\022\027com.zc.web.message.deb" +
      "t\"q\n\014ListRepayReq\022\014\n\004page\030\001 \001(\005\022\016\n\006debtI" +
      "d\030\002 \001(\t\022\017\n\007ownerId\030\003 \001(\t\022\020\n\010deputyId\030\004 \001" +
      "(\t\022\020\n\010timeFrom\030\005 \001(\005\022\016\n\006timeTo\030\006 \001(\005B\023B\021" +
      "ListRepayReqProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zc_web_message_debt_ListRepayReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zc_web_message_debt_ListRepayReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zc_web_message_debt_ListRepayReq_descriptor,
              new java.lang.String[] { "Page", "DebtId", "OwnerId", "DeputyId", "TimeFrom", "TimeTo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
