// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/com/zc/messages/debt/ListRepayRsp.proto

package com.zc.web.message.debt;

public final class ListRepayRspProto {
  private ListRepayRspProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ListRepayRspOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;
    /**
     * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
     */
    java.util.List<com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg> 
        getRepayList();
    /**
     * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
     */
    com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg getRepay(int index);
    /**
     * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
     */
    int getRepayCount();
    /**
     * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
     */
    java.util.List<? extends com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsgOrBuilder> 
        getRepayOrBuilderList();
    /**
     * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
     */
    com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsgOrBuilder getRepayOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.zc.web.message.debt.ListRepayRsp}
   */
  public static final class ListRepayRsp extends
      com.google.protobuf.GeneratedMessage
      implements ListRepayRspOrBuilder {
    // Use ListRepayRsp.newBuilder() to construct.
    private ListRepayRsp(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ListRepayRsp(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ListRepayRsp defaultInstance;
    public static ListRepayRsp getDefaultInstance() {
      return defaultInstance;
    }

    public ListRepayRsp getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ListRepayRsp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                repay_ = new java.util.ArrayList<com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg>();
                mutable_bitField0_ |= 0x00000001;
              }
              repay_.add(input.readMessage(com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          repay_ = java.util.Collections.unmodifiableList(repay_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zc.web.message.debt.ListRepayRspProto.internal_static_com_zc_web_message_debt_ListRepayRsp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zc.web.message.debt.ListRepayRspProto.internal_static_com_zc_web_message_debt_ListRepayRsp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.class, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.Builder.class);
    }

    public static com.google.protobuf.Parser<ListRepayRsp> PARSER =
        new com.google.protobuf.AbstractParser<ListRepayRsp>() {
      public ListRepayRsp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListRepayRsp(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ListRepayRsp> getParserForType() {
      return PARSER;
    }

    public interface RepayMsgOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional int64 debtId = 1;
      /**
       * <code>optional int64 debtId = 1;</code>
       *
       * <pre>
       * debtId
       * </pre>
       */
      boolean hasDebtId();
      /**
       * <code>optional int64 debtId = 1;</code>
       *
       * <pre>
       * debtId
       * </pre>
       */
      long getDebtId();

      // optional int64 ownerId = 2;
      /**
       * <code>optional int64 ownerId = 2;</code>
       *
       * <pre>
       * 发布人
       * </pre>
       */
      boolean hasOwnerId();
      /**
       * <code>optional int64 ownerId = 2;</code>
       *
       * <pre>
       * 发布人
       * </pre>
       */
      long getOwnerId();

      // optional int64 deputyId = 3;
      /**
       * <code>optional int64 deputyId = 3;</code>
       *
       * <pre>
       * 中标人
       * </pre>
       */
      boolean hasDeputyId();
      /**
       * <code>optional int64 deputyId = 3;</code>
       *
       * <pre>
       * 中标人
       * </pre>
       */
      long getDeputyId();

      // optional int32 money = 4;
      /**
       * <code>optional int32 money = 4;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      boolean hasMoney();
      /**
       * <code>optional int32 money = 4;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      int getMoney();

      // optional int32 state = 5;
      /**
       * <code>optional int32 state = 5;</code>
       *
       * <pre>
       * 状态
       * </pre>
       */
      boolean hasState();
      /**
       * <code>optional int32 state = 5;</code>
       *
       * <pre>
       * 状态
       * </pre>
       */
      int getState();

      // optional int32 receiveTime = 6;
      /**
       * <code>optional int32 receiveTime = 6;</code>
       *
       * <pre>
       * 接单时间
       * </pre>
       */
      boolean hasReceiveTime();
      /**
       * <code>optional int32 receiveTime = 6;</code>
       *
       * <pre>
       * 接单时间
       * </pre>
       */
      int getReceiveTime();

      // optional string creditorName = 7;
      /**
       * <code>optional string creditorName = 7;</code>
       *
       * <pre>
       *债权人
       * </pre>
       */
      boolean hasCreditorName();
      /**
       * <code>optional string creditorName = 7;</code>
       *
       * <pre>
       *债权人
       * </pre>
       */
      java.lang.String getCreditorName();
      /**
       * <code>optional string creditorName = 7;</code>
       *
       * <pre>
       *债权人
       * </pre>
       */
      com.google.protobuf.ByteString
          getCreditorNameBytes();

      // optional int32 time = 8;
      /**
       * <code>optional int32 time = 8;</code>
       *
       * <pre>
       * 还款时间
       * </pre>
       */
      boolean hasTime();
      /**
       * <code>optional int32 time = 8;</code>
       *
       * <pre>
       * 还款时间
       * </pre>
       */
      int getTime();

      // optional int32 repayMoney = 9;
      /**
       * <code>optional int32 repayMoney = 9;</code>
       *
       * <pre>
       * 还款金额
       * </pre>
       */
      boolean hasRepayMoney();
      /**
       * <code>optional int32 repayMoney = 9;</code>
       *
       * <pre>
       * 还款金额
       * </pre>
       */
      int getRepayMoney();

      // optional string memo = 10;
      /**
       * <code>optional string memo = 10;</code>
       *
       * <pre>
       * 还款说明
       * </pre>
       */
      boolean hasMemo();
      /**
       * <code>optional string memo = 10;</code>
       *
       * <pre>
       * 还款说明
       * </pre>
       */
      java.lang.String getMemo();
      /**
       * <code>optional string memo = 10;</code>
       *
       * <pre>
       * 还款说明
       * </pre>
       */
      com.google.protobuf.ByteString
          getMemoBytes();
    }
    /**
     * Protobuf type {@code com.zc.web.message.debt.ListRepayRsp.RepayMsg}
     */
    public static final class RepayMsg extends
        com.google.protobuf.GeneratedMessage
        implements RepayMsgOrBuilder {
      // Use RepayMsg.newBuilder() to construct.
      private RepayMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private RepayMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final RepayMsg defaultInstance;
      public static RepayMsg getDefaultInstance() {
        return defaultInstance;
      }

      public RepayMsg getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private RepayMsg(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                bitField0_ |= 0x00000001;
                debtId_ = input.readInt64();
                break;
              }
              case 16: {
                bitField0_ |= 0x00000002;
                ownerId_ = input.readInt64();
                break;
              }
              case 24: {
                bitField0_ |= 0x00000004;
                deputyId_ = input.readInt64();
                break;
              }
              case 32: {
                bitField0_ |= 0x00000008;
                money_ = input.readInt32();
                break;
              }
              case 40: {
                bitField0_ |= 0x00000010;
                state_ = input.readInt32();
                break;
              }
              case 48: {
                bitField0_ |= 0x00000020;
                receiveTime_ = input.readInt32();
                break;
              }
              case 58: {
                bitField0_ |= 0x00000040;
                creditorName_ = input.readBytes();
                break;
              }
              case 64: {
                bitField0_ |= 0x00000080;
                time_ = input.readInt32();
                break;
              }
              case 72: {
                bitField0_ |= 0x00000100;
                repayMoney_ = input.readInt32();
                break;
              }
              case 82: {
                bitField0_ |= 0x00000200;
                memo_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zc.web.message.debt.ListRepayRspProto.internal_static_com_zc_web_message_debt_ListRepayRsp_RepayMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zc.web.message.debt.ListRepayRspProto.internal_static_com_zc_web_message_debt_ListRepayRsp_RepayMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.class, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder.class);
      }

      public static com.google.protobuf.Parser<RepayMsg> PARSER =
          new com.google.protobuf.AbstractParser<RepayMsg>() {
        public RepayMsg parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new RepayMsg(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<RepayMsg> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional int64 debtId = 1;
      public static final int DEBTID_FIELD_NUMBER = 1;
      private long debtId_;
      /**
       * <code>optional int64 debtId = 1;</code>
       *
       * <pre>
       * debtId
       * </pre>
       */
      public boolean hasDebtId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int64 debtId = 1;</code>
       *
       * <pre>
       * debtId
       * </pre>
       */
      public long getDebtId() {
        return debtId_;
      }

      // optional int64 ownerId = 2;
      public static final int OWNERID_FIELD_NUMBER = 2;
      private long ownerId_;
      /**
       * <code>optional int64 ownerId = 2;</code>
       *
       * <pre>
       * 发布人
       * </pre>
       */
      public boolean hasOwnerId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 ownerId = 2;</code>
       *
       * <pre>
       * 发布人
       * </pre>
       */
      public long getOwnerId() {
        return ownerId_;
      }

      // optional int64 deputyId = 3;
      public static final int DEPUTYID_FIELD_NUMBER = 3;
      private long deputyId_;
      /**
       * <code>optional int64 deputyId = 3;</code>
       *
       * <pre>
       * 中标人
       * </pre>
       */
      public boolean hasDeputyId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int64 deputyId = 3;</code>
       *
       * <pre>
       * 中标人
       * </pre>
       */
      public long getDeputyId() {
        return deputyId_;
      }

      // optional int32 money = 4;
      public static final int MONEY_FIELD_NUMBER = 4;
      private int money_;
      /**
       * <code>optional int32 money = 4;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      public boolean hasMoney() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int32 money = 4;</code>
       *
       * <pre>
       * 金额
       * </pre>
       */
      public int getMoney() {
        return money_;
      }

      // optional int32 state = 5;
      public static final int STATE_FIELD_NUMBER = 5;
      private int state_;
      /**
       * <code>optional int32 state = 5;</code>
       *
       * <pre>
       * 状态
       * </pre>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 state = 5;</code>
       *
       * <pre>
       * 状态
       * </pre>
       */
      public int getState() {
        return state_;
      }

      // optional int32 receiveTime = 6;
      public static final int RECEIVETIME_FIELD_NUMBER = 6;
      private int receiveTime_;
      /**
       * <code>optional int32 receiveTime = 6;</code>
       *
       * <pre>
       * 接单时间
       * </pre>
       */
      public boolean hasReceiveTime() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional int32 receiveTime = 6;</code>
       *
       * <pre>
       * 接单时间
       * </pre>
       */
      public int getReceiveTime() {
        return receiveTime_;
      }

      // optional string creditorName = 7;
      public static final int CREDITORNAME_FIELD_NUMBER = 7;
      private java.lang.Object creditorName_;
      /**
       * <code>optional string creditorName = 7;</code>
       *
       * <pre>
       *债权人
       * </pre>
       */
      public boolean hasCreditorName() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional string creditorName = 7;</code>
       *
       * <pre>
       *债权人
       * </pre>
       */
      public java.lang.String getCreditorName() {
        java.lang.Object ref = creditorName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            creditorName_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string creditorName = 7;</code>
       *
       * <pre>
       *债权人
       * </pre>
       */
      public com.google.protobuf.ByteString
          getCreditorNameBytes() {
        java.lang.Object ref = creditorName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          creditorName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional int32 time = 8;
      public static final int TIME_FIELD_NUMBER = 8;
      private int time_;
      /**
       * <code>optional int32 time = 8;</code>
       *
       * <pre>
       * 还款时间
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional int32 time = 8;</code>
       *
       * <pre>
       * 还款时间
       * </pre>
       */
      public int getTime() {
        return time_;
      }

      // optional int32 repayMoney = 9;
      public static final int REPAYMONEY_FIELD_NUMBER = 9;
      private int repayMoney_;
      /**
       * <code>optional int32 repayMoney = 9;</code>
       *
       * <pre>
       * 还款金额
       * </pre>
       */
      public boolean hasRepayMoney() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional int32 repayMoney = 9;</code>
       *
       * <pre>
       * 还款金额
       * </pre>
       */
      public int getRepayMoney() {
        return repayMoney_;
      }

      // optional string memo = 10;
      public static final int MEMO_FIELD_NUMBER = 10;
      private java.lang.Object memo_;
      /**
       * <code>optional string memo = 10;</code>
       *
       * <pre>
       * 还款说明
       * </pre>
       */
      public boolean hasMemo() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional string memo = 10;</code>
       *
       * <pre>
       * 还款说明
       * </pre>
       */
      public java.lang.String getMemo() {
        java.lang.Object ref = memo_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            memo_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string memo = 10;</code>
       *
       * <pre>
       * 还款说明
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMemoBytes() {
        java.lang.Object ref = memo_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        debtId_ = 0L;
        ownerId_ = 0L;
        deputyId_ = 0L;
        money_ = 0;
        state_ = 0;
        receiveTime_ = 0;
        creditorName_ = "";
        time_ = 0;
        repayMoney_ = 0;
        memo_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeInt64(1, debtId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeInt64(2, ownerId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeInt64(3, deputyId_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeInt32(4, money_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeInt32(5, state_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          output.writeInt32(6, receiveTime_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          output.writeBytes(7, getCreditorNameBytes());
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          output.writeInt32(8, time_);
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          output.writeInt32(9, repayMoney_);
        }
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          output.writeBytes(10, getMemoBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(1, debtId_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, ownerId_);
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(3, deputyId_);
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(4, money_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(5, state_);
        }
        if (((bitField0_ & 0x00000020) == 0x00000020)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(6, receiveTime_);
        }
        if (((bitField0_ & 0x00000040) == 0x00000040)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(7, getCreditorNameBytes());
        }
        if (((bitField0_ & 0x00000080) == 0x00000080)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(8, time_);
        }
        if (((bitField0_ & 0x00000100) == 0x00000100)) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt32Size(9, repayMoney_);
        }
        if (((bitField0_ & 0x00000200) == 0x00000200)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(10, getMemoBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.zc.web.message.debt.ListRepayRsp.RepayMsg}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsgOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.zc.web.message.debt.ListRepayRspProto.internal_static_com_zc_web_message_debt_ListRepayRsp_RepayMsg_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.zc.web.message.debt.ListRepayRspProto.internal_static_com_zc_web_message_debt_ListRepayRsp_RepayMsg_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.class, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder.class);
        }

        // Construct using com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          debtId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000001);
          ownerId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000002);
          deputyId_ = 0L;
          bitField0_ = (bitField0_ & ~0x00000004);
          money_ = 0;
          bitField0_ = (bitField0_ & ~0x00000008);
          state_ = 0;
          bitField0_ = (bitField0_ & ~0x00000010);
          receiveTime_ = 0;
          bitField0_ = (bitField0_ & ~0x00000020);
          creditorName_ = "";
          bitField0_ = (bitField0_ & ~0x00000040);
          time_ = 0;
          bitField0_ = (bitField0_ & ~0x00000080);
          repayMoney_ = 0;
          bitField0_ = (bitField0_ & ~0x00000100);
          memo_ = "";
          bitField0_ = (bitField0_ & ~0x00000200);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.zc.web.message.debt.ListRepayRspProto.internal_static_com_zc_web_message_debt_ListRepayRsp_RepayMsg_descriptor;
        }

        public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg getDefaultInstanceForType() {
          return com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.getDefaultInstance();
        }

        public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg build() {
          com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg buildPartial() {
          com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg result = new com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.debtId_ = debtId_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.ownerId_ = ownerId_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.deputyId_ = deputyId_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.money_ = money_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.state_ = state_;
          if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
            to_bitField0_ |= 0x00000020;
          }
          result.receiveTime_ = receiveTime_;
          if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
            to_bitField0_ |= 0x00000040;
          }
          result.creditorName_ = creditorName_;
          if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
            to_bitField0_ |= 0x00000080;
          }
          result.time_ = time_;
          if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
            to_bitField0_ |= 0x00000100;
          }
          result.repayMoney_ = repayMoney_;
          if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
            to_bitField0_ |= 0x00000200;
          }
          result.memo_ = memo_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg) {
            return mergeFrom((com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg other) {
          if (other == com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.getDefaultInstance()) return this;
          if (other.hasDebtId()) {
            setDebtId(other.getDebtId());
          }
          if (other.hasOwnerId()) {
            setOwnerId(other.getOwnerId());
          }
          if (other.hasDeputyId()) {
            setDeputyId(other.getDeputyId());
          }
          if (other.hasMoney()) {
            setMoney(other.getMoney());
          }
          if (other.hasState()) {
            setState(other.getState());
          }
          if (other.hasReceiveTime()) {
            setReceiveTime(other.getReceiveTime());
          }
          if (other.hasCreditorName()) {
            bitField0_ |= 0x00000040;
            creditorName_ = other.creditorName_;
            onChanged();
          }
          if (other.hasTime()) {
            setTime(other.getTime());
          }
          if (other.hasRepayMoney()) {
            setRepayMoney(other.getRepayMoney());
          }
          if (other.hasMemo()) {
            bitField0_ |= 0x00000200;
            memo_ = other.memo_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional int64 debtId = 1;
        private long debtId_ ;
        /**
         * <code>optional int64 debtId = 1;</code>
         *
         * <pre>
         * debtId
         * </pre>
         */
        public boolean hasDebtId() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional int64 debtId = 1;</code>
         *
         * <pre>
         * debtId
         * </pre>
         */
        public long getDebtId() {
          return debtId_;
        }
        /**
         * <code>optional int64 debtId = 1;</code>
         *
         * <pre>
         * debtId
         * </pre>
         */
        public Builder setDebtId(long value) {
          bitField0_ |= 0x00000001;
          debtId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 debtId = 1;</code>
         *
         * <pre>
         * debtId
         * </pre>
         */
        public Builder clearDebtId() {
          bitField0_ = (bitField0_ & ~0x00000001);
          debtId_ = 0L;
          onChanged();
          return this;
        }

        // optional int64 ownerId = 2;
        private long ownerId_ ;
        /**
         * <code>optional int64 ownerId = 2;</code>
         *
         * <pre>
         * 发布人
         * </pre>
         */
        public boolean hasOwnerId() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional int64 ownerId = 2;</code>
         *
         * <pre>
         * 发布人
         * </pre>
         */
        public long getOwnerId() {
          return ownerId_;
        }
        /**
         * <code>optional int64 ownerId = 2;</code>
         *
         * <pre>
         * 发布人
         * </pre>
         */
        public Builder setOwnerId(long value) {
          bitField0_ |= 0x00000002;
          ownerId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 ownerId = 2;</code>
         *
         * <pre>
         * 发布人
         * </pre>
         */
        public Builder clearOwnerId() {
          bitField0_ = (bitField0_ & ~0x00000002);
          ownerId_ = 0L;
          onChanged();
          return this;
        }

        // optional int64 deputyId = 3;
        private long deputyId_ ;
        /**
         * <code>optional int64 deputyId = 3;</code>
         *
         * <pre>
         * 中标人
         * </pre>
         */
        public boolean hasDeputyId() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional int64 deputyId = 3;</code>
         *
         * <pre>
         * 中标人
         * </pre>
         */
        public long getDeputyId() {
          return deputyId_;
        }
        /**
         * <code>optional int64 deputyId = 3;</code>
         *
         * <pre>
         * 中标人
         * </pre>
         */
        public Builder setDeputyId(long value) {
          bitField0_ |= 0x00000004;
          deputyId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int64 deputyId = 3;</code>
         *
         * <pre>
         * 中标人
         * </pre>
         */
        public Builder clearDeputyId() {
          bitField0_ = (bitField0_ & ~0x00000004);
          deputyId_ = 0L;
          onChanged();
          return this;
        }

        // optional int32 money = 4;
        private int money_ ;
        /**
         * <code>optional int32 money = 4;</code>
         *
         * <pre>
         * 金额
         * </pre>
         */
        public boolean hasMoney() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional int32 money = 4;</code>
         *
         * <pre>
         * 金额
         * </pre>
         */
        public int getMoney() {
          return money_;
        }
        /**
         * <code>optional int32 money = 4;</code>
         *
         * <pre>
         * 金额
         * </pre>
         */
        public Builder setMoney(int value) {
          bitField0_ |= 0x00000008;
          money_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 money = 4;</code>
         *
         * <pre>
         * 金额
         * </pre>
         */
        public Builder clearMoney() {
          bitField0_ = (bitField0_ & ~0x00000008);
          money_ = 0;
          onChanged();
          return this;
        }

        // optional int32 state = 5;
        private int state_ ;
        /**
         * <code>optional int32 state = 5;</code>
         *
         * <pre>
         * 状态
         * </pre>
         */
        public boolean hasState() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional int32 state = 5;</code>
         *
         * <pre>
         * 状态
         * </pre>
         */
        public int getState() {
          return state_;
        }
        /**
         * <code>optional int32 state = 5;</code>
         *
         * <pre>
         * 状态
         * </pre>
         */
        public Builder setState(int value) {
          bitField0_ |= 0x00000010;
          state_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 state = 5;</code>
         *
         * <pre>
         * 状态
         * </pre>
         */
        public Builder clearState() {
          bitField0_ = (bitField0_ & ~0x00000010);
          state_ = 0;
          onChanged();
          return this;
        }

        // optional int32 receiveTime = 6;
        private int receiveTime_ ;
        /**
         * <code>optional int32 receiveTime = 6;</code>
         *
         * <pre>
         * 接单时间
         * </pre>
         */
        public boolean hasReceiveTime() {
          return ((bitField0_ & 0x00000020) == 0x00000020);
        }
        /**
         * <code>optional int32 receiveTime = 6;</code>
         *
         * <pre>
         * 接单时间
         * </pre>
         */
        public int getReceiveTime() {
          return receiveTime_;
        }
        /**
         * <code>optional int32 receiveTime = 6;</code>
         *
         * <pre>
         * 接单时间
         * </pre>
         */
        public Builder setReceiveTime(int value) {
          bitField0_ |= 0x00000020;
          receiveTime_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 receiveTime = 6;</code>
         *
         * <pre>
         * 接单时间
         * </pre>
         */
        public Builder clearReceiveTime() {
          bitField0_ = (bitField0_ & ~0x00000020);
          receiveTime_ = 0;
          onChanged();
          return this;
        }

        // optional string creditorName = 7;
        private java.lang.Object creditorName_ = "";
        /**
         * <code>optional string creditorName = 7;</code>
         *
         * <pre>
         *债权人
         * </pre>
         */
        public boolean hasCreditorName() {
          return ((bitField0_ & 0x00000040) == 0x00000040);
        }
        /**
         * <code>optional string creditorName = 7;</code>
         *
         * <pre>
         *债权人
         * </pre>
         */
        public java.lang.String getCreditorName() {
          java.lang.Object ref = creditorName_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            creditorName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string creditorName = 7;</code>
         *
         * <pre>
         *债权人
         * </pre>
         */
        public com.google.protobuf.ByteString
            getCreditorNameBytes() {
          java.lang.Object ref = creditorName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            creditorName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string creditorName = 7;</code>
         *
         * <pre>
         *债权人
         * </pre>
         */
        public Builder setCreditorName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          creditorName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string creditorName = 7;</code>
         *
         * <pre>
         *债权人
         * </pre>
         */
        public Builder clearCreditorName() {
          bitField0_ = (bitField0_ & ~0x00000040);
          creditorName_ = getDefaultInstance().getCreditorName();
          onChanged();
          return this;
        }
        /**
         * <code>optional string creditorName = 7;</code>
         *
         * <pre>
         *债权人
         * </pre>
         */
        public Builder setCreditorNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
          creditorName_ = value;
          onChanged();
          return this;
        }

        // optional int32 time = 8;
        private int time_ ;
        /**
         * <code>optional int32 time = 8;</code>
         *
         * <pre>
         * 还款时间
         * </pre>
         */
        public boolean hasTime() {
          return ((bitField0_ & 0x00000080) == 0x00000080);
        }
        /**
         * <code>optional int32 time = 8;</code>
         *
         * <pre>
         * 还款时间
         * </pre>
         */
        public int getTime() {
          return time_;
        }
        /**
         * <code>optional int32 time = 8;</code>
         *
         * <pre>
         * 还款时间
         * </pre>
         */
        public Builder setTime(int value) {
          bitField0_ |= 0x00000080;
          time_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 time = 8;</code>
         *
         * <pre>
         * 还款时间
         * </pre>
         */
        public Builder clearTime() {
          bitField0_ = (bitField0_ & ~0x00000080);
          time_ = 0;
          onChanged();
          return this;
        }

        // optional int32 repayMoney = 9;
        private int repayMoney_ ;
        /**
         * <code>optional int32 repayMoney = 9;</code>
         *
         * <pre>
         * 还款金额
         * </pre>
         */
        public boolean hasRepayMoney() {
          return ((bitField0_ & 0x00000100) == 0x00000100);
        }
        /**
         * <code>optional int32 repayMoney = 9;</code>
         *
         * <pre>
         * 还款金额
         * </pre>
         */
        public int getRepayMoney() {
          return repayMoney_;
        }
        /**
         * <code>optional int32 repayMoney = 9;</code>
         *
         * <pre>
         * 还款金额
         * </pre>
         */
        public Builder setRepayMoney(int value) {
          bitField0_ |= 0x00000100;
          repayMoney_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional int32 repayMoney = 9;</code>
         *
         * <pre>
         * 还款金额
         * </pre>
         */
        public Builder clearRepayMoney() {
          bitField0_ = (bitField0_ & ~0x00000100);
          repayMoney_ = 0;
          onChanged();
          return this;
        }

        // optional string memo = 10;
        private java.lang.Object memo_ = "";
        /**
         * <code>optional string memo = 10;</code>
         *
         * <pre>
         * 还款说明
         * </pre>
         */
        public boolean hasMemo() {
          return ((bitField0_ & 0x00000200) == 0x00000200);
        }
        /**
         * <code>optional string memo = 10;</code>
         *
         * <pre>
         * 还款说明
         * </pre>
         */
        public java.lang.String getMemo() {
          java.lang.Object ref = memo_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            memo_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string memo = 10;</code>
         *
         * <pre>
         * 还款说明
         * </pre>
         */
        public com.google.protobuf.ByteString
            getMemoBytes() {
          java.lang.Object ref = memo_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            memo_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string memo = 10;</code>
         *
         * <pre>
         * 还款说明
         * </pre>
         */
        public Builder setMemo(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
          memo_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string memo = 10;</code>
         *
         * <pre>
         * 还款说明
         * </pre>
         */
        public Builder clearMemo() {
          bitField0_ = (bitField0_ & ~0x00000200);
          memo_ = getDefaultInstance().getMemo();
          onChanged();
          return this;
        }
        /**
         * <code>optional string memo = 10;</code>
         *
         * <pre>
         * 还款说明
         * </pre>
         */
        public Builder setMemoBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000200;
          memo_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:com.zc.web.message.debt.ListRepayRsp.RepayMsg)
      }

      static {
        defaultInstance = new RepayMsg(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:com.zc.web.message.debt.ListRepayRsp.RepayMsg)
    }

    // repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;
    public static final int REPAY_FIELD_NUMBER = 1;
    private java.util.List<com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg> repay_;
    /**
     * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
     */
    public java.util.List<com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg> getRepayList() {
      return repay_;
    }
    /**
     * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
     */
    public java.util.List<? extends com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsgOrBuilder> 
        getRepayOrBuilderList() {
      return repay_;
    }
    /**
     * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
     */
    public int getRepayCount() {
      return repay_.size();
    }
    /**
     * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
     */
    public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg getRepay(int index) {
      return repay_.get(index);
    }
    /**
     * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
     */
    public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsgOrBuilder getRepayOrBuilder(
        int index) {
      return repay_.get(index);
    }

    private void initFields() {
      repay_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < repay_.size(); i++) {
        output.writeMessage(1, repay_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < repay_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, repay_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zc.web.message.debt.ListRepayRsp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zc.web.message.debt.ListRepayRspProto.ListRepayRspOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zc.web.message.debt.ListRepayRspProto.internal_static_com_zc_web_message_debt_ListRepayRsp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zc.web.message.debt.ListRepayRspProto.internal_static_com_zc_web_message_debt_ListRepayRsp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.class, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.Builder.class);
      }

      // Construct using com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getRepayFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (repayBuilder_ == null) {
          repay_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          repayBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zc.web.message.debt.ListRepayRspProto.internal_static_com_zc_web_message_debt_ListRepayRsp_descriptor;
      }

      public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp getDefaultInstanceForType() {
        return com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.getDefaultInstance();
      }

      public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp build() {
        com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp buildPartial() {
        com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp result = new com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp(this);
        int from_bitField0_ = bitField0_;
        if (repayBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            repay_ = java.util.Collections.unmodifiableList(repay_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.repay_ = repay_;
        } else {
          result.repay_ = repayBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp) {
          return mergeFrom((com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp other) {
        if (other == com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.getDefaultInstance()) return this;
        if (repayBuilder_ == null) {
          if (!other.repay_.isEmpty()) {
            if (repay_.isEmpty()) {
              repay_ = other.repay_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureRepayIsMutable();
              repay_.addAll(other.repay_);
            }
            onChanged();
          }
        } else {
          if (!other.repay_.isEmpty()) {
            if (repayBuilder_.isEmpty()) {
              repayBuilder_.dispose();
              repayBuilder_ = null;
              repay_ = other.repay_;
              bitField0_ = (bitField0_ & ~0x00000001);
              repayBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getRepayFieldBuilder() : null;
            } else {
              repayBuilder_.addAllMessages(other.repay_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;
      private java.util.List<com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg> repay_ =
        java.util.Collections.emptyList();
      private void ensureRepayIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          repay_ = new java.util.ArrayList<com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg>(repay_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsgOrBuilder> repayBuilder_;

      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public java.util.List<com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg> getRepayList() {
        if (repayBuilder_ == null) {
          return java.util.Collections.unmodifiableList(repay_);
        } else {
          return repayBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public int getRepayCount() {
        if (repayBuilder_ == null) {
          return repay_.size();
        } else {
          return repayBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg getRepay(int index) {
        if (repayBuilder_ == null) {
          return repay_.get(index);
        } else {
          return repayBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public Builder setRepay(
          int index, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg value) {
        if (repayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRepayIsMutable();
          repay_.set(index, value);
          onChanged();
        } else {
          repayBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public Builder setRepay(
          int index, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder builderForValue) {
        if (repayBuilder_ == null) {
          ensureRepayIsMutable();
          repay_.set(index, builderForValue.build());
          onChanged();
        } else {
          repayBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public Builder addRepay(com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg value) {
        if (repayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRepayIsMutable();
          repay_.add(value);
          onChanged();
        } else {
          repayBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public Builder addRepay(
          int index, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg value) {
        if (repayBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureRepayIsMutable();
          repay_.add(index, value);
          onChanged();
        } else {
          repayBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public Builder addRepay(
          com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder builderForValue) {
        if (repayBuilder_ == null) {
          ensureRepayIsMutable();
          repay_.add(builderForValue.build());
          onChanged();
        } else {
          repayBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public Builder addRepay(
          int index, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder builderForValue) {
        if (repayBuilder_ == null) {
          ensureRepayIsMutable();
          repay_.add(index, builderForValue.build());
          onChanged();
        } else {
          repayBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public Builder addAllRepay(
          java.lang.Iterable<? extends com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg> values) {
        if (repayBuilder_ == null) {
          ensureRepayIsMutable();
          super.addAll(values, repay_);
          onChanged();
        } else {
          repayBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public Builder clearRepay() {
        if (repayBuilder_ == null) {
          repay_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          repayBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public Builder removeRepay(int index) {
        if (repayBuilder_ == null) {
          ensureRepayIsMutable();
          repay_.remove(index);
          onChanged();
        } else {
          repayBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder getRepayBuilder(
          int index) {
        return getRepayFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsgOrBuilder getRepayOrBuilder(
          int index) {
        if (repayBuilder_ == null) {
          return repay_.get(index);  } else {
          return repayBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public java.util.List<? extends com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsgOrBuilder> 
           getRepayOrBuilderList() {
        if (repayBuilder_ != null) {
          return repayBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(repay_);
        }
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder addRepayBuilder() {
        return getRepayFieldBuilder().addBuilder(
            com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder addRepayBuilder(
          int index) {
        return getRepayFieldBuilder().addBuilder(
            index, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zc.web.message.debt.ListRepayRsp.RepayMsg repay = 1;</code>
       */
      public java.util.List<com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder> 
           getRepayBuilderList() {
        return getRepayFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsgOrBuilder> 
          getRepayFieldBuilder() {
        if (repayBuilder_ == null) {
          repayBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsg.Builder, com.zc.web.message.debt.ListRepayRspProto.ListRepayRsp.RepayMsgOrBuilder>(
                  repay_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          repay_ = null;
        }
        return repayBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.zc.web.message.debt.ListRepayRsp)
    }

    static {
      defaultInstance = new ListRepayRsp(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zc.web.message.debt.ListRepayRsp)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zc_web_message_debt_ListRepayRsp_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zc_web_message_debt_ListRepayRsp_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zc_web_message_debt_ListRepayRsp_RepayMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zc_web_message_debt_ListRepayRsp_RepayMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6main/resources/com/zc/messages/debt/Li" +
      "stRepayRsp.proto\022\027com.zc.web.message.deb" +
      "t\"\206\002\n\014ListRepayRsp\022=\n\005repay\030\001 \003(\0132..com." +
      "zc.web.message.debt.ListRepayRsp.RepayMs" +
      "g\032\266\001\n\010RepayMsg\022\016\n\006debtId\030\001 \001(\003\022\017\n\007ownerI" +
      "d\030\002 \001(\003\022\020\n\010deputyId\030\003 \001(\003\022\r\n\005money\030\004 \001(\005" +
      "\022\r\n\005state\030\005 \001(\005\022\023\n\013receiveTime\030\006 \001(\005\022\024\n\014" +
      "creditorName\030\007 \001(\t\022\014\n\004time\030\010 \001(\005\022\022\n\nrepa" +
      "yMoney\030\t \001(\005\022\014\n\004memo\030\n \001(\tB\023B\021ListRepayR" +
      "spProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zc_web_message_debt_ListRepayRsp_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zc_web_message_debt_ListRepayRsp_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zc_web_message_debt_ListRepayRsp_descriptor,
              new java.lang.String[] { "Repay", });
          internal_static_com_zc_web_message_debt_ListRepayRsp_RepayMsg_descriptor =
            internal_static_com_zc_web_message_debt_ListRepayRsp_descriptor.getNestedTypes().get(0);
          internal_static_com_zc_web_message_debt_ListRepayRsp_RepayMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zc_web_message_debt_ListRepayRsp_RepayMsg_descriptor,
              new java.lang.String[] { "DebtId", "OwnerId", "DeputyId", "Money", "State", "ReceiveTime", "CreditorName", "Time", "RepayMoney", "Memo", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
