// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/com/zc/messages/player/ListMoneyHistoryReq.proto

package com.zc.web.message.debt;

public final class ListMoneyHistoryReqProto {
  private ListMoneyHistoryReqProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ListMoneyHistoryReqOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 timeFrom = 1;
    /**
     * <code>optional int32 timeFrom = 1;</code>
     *
     * <pre>
     * 时间（起）
     * </pre>
     */
    boolean hasTimeFrom();
    /**
     * <code>optional int32 timeFrom = 1;</code>
     *
     * <pre>
     * 时间（起）
     * </pre>
     */
    int getTimeFrom();

    // optional int32 timeTo = 2;
    /**
     * <code>optional int32 timeTo = 2;</code>
     *
     * <pre>
     * 时间（止）
     * </pre>
     */
    boolean hasTimeTo();
    /**
     * <code>optional int32 timeTo = 2;</code>
     *
     * <pre>
     * 时间（止）
     * </pre>
     */
    int getTimeTo();

    // optional int32 type = 3;
    /**
     * <code>optional int32 type = 3;</code>
     *
     * <pre>
     * 1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 3;</code>
     *
     * <pre>
     * 1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
     * </pre>
     */
    int getType();
  }
  /**
   * Protobuf type {@code com.zc.web.message.debt.ListMoneyHistoryReq}
   */
  public static final class ListMoneyHistoryReq extends
      com.google.protobuf.GeneratedMessage
      implements ListMoneyHistoryReqOrBuilder {
    // Use ListMoneyHistoryReq.newBuilder() to construct.
    private ListMoneyHistoryReq(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ListMoneyHistoryReq(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ListMoneyHistoryReq defaultInstance;
    public static ListMoneyHistoryReq getDefaultInstance() {
      return defaultInstance;
    }

    public ListMoneyHistoryReq getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ListMoneyHistoryReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              timeFrom_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timeTo_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zc.web.message.debt.ListMoneyHistoryReqProto.internal_static_com_zc_web_message_debt_ListMoneyHistoryReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zc.web.message.debt.ListMoneyHistoryReqProto.internal_static_com_zc_web_message_debt_ListMoneyHistoryReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq.class, com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq.Builder.class);
    }

    public static com.google.protobuf.Parser<ListMoneyHistoryReq> PARSER =
        new com.google.protobuf.AbstractParser<ListMoneyHistoryReq>() {
      public ListMoneyHistoryReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ListMoneyHistoryReq(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ListMoneyHistoryReq> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 timeFrom = 1;
    public static final int TIMEFROM_FIELD_NUMBER = 1;
    private int timeFrom_;
    /**
     * <code>optional int32 timeFrom = 1;</code>
     *
     * <pre>
     * 时间（起）
     * </pre>
     */
    public boolean hasTimeFrom() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 timeFrom = 1;</code>
     *
     * <pre>
     * 时间（起）
     * </pre>
     */
    public int getTimeFrom() {
      return timeFrom_;
    }

    // optional int32 timeTo = 2;
    public static final int TIMETO_FIELD_NUMBER = 2;
    private int timeTo_;
    /**
     * <code>optional int32 timeTo = 2;</code>
     *
     * <pre>
     * 时间（止）
     * </pre>
     */
    public boolean hasTimeTo() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 timeTo = 2;</code>
     *
     * <pre>
     * 时间（止）
     * </pre>
     */
    public int getTimeTo() {
      return timeTo_;
    }

    // optional int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional int32 type = 3;</code>
     *
     * <pre>
     * 1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 type = 3;</code>
     *
     * <pre>
     * 1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
     * </pre>
     */
    public int getType() {
      return type_;
    }

    private void initFields() {
      timeFrom_ = 0;
      timeTo_ = 0;
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, timeFrom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, timeTo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, type_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, timeFrom_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, timeTo_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zc.web.message.debt.ListMoneyHistoryReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zc.web.message.debt.ListMoneyHistoryReqProto.internal_static_com_zc_web_message_debt_ListMoneyHistoryReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zc.web.message.debt.ListMoneyHistoryReqProto.internal_static_com_zc_web_message_debt_ListMoneyHistoryReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq.class, com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq.Builder.class);
      }

      // Construct using com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timeFrom_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        timeTo_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zc.web.message.debt.ListMoneyHistoryReqProto.internal_static_com_zc_web_message_debt_ListMoneyHistoryReq_descriptor;
      }

      public com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq getDefaultInstanceForType() {
        return com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq.getDefaultInstance();
      }

      public com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq build() {
        com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq buildPartial() {
        com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq result = new com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timeFrom_ = timeFrom_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timeTo_ = timeTo_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq) {
          return mergeFrom((com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq other) {
        if (other == com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq.getDefaultInstance()) return this;
        if (other.hasTimeFrom()) {
          setTimeFrom(other.getTimeFrom());
        }
        if (other.hasTimeTo()) {
          setTimeTo(other.getTimeTo());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zc.web.message.debt.ListMoneyHistoryReqProto.ListMoneyHistoryReq) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 timeFrom = 1;
      private int timeFrom_ ;
      /**
       * <code>optional int32 timeFrom = 1;</code>
       *
       * <pre>
       * 时间（起）
       * </pre>
       */
      public boolean hasTimeFrom() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 timeFrom = 1;</code>
       *
       * <pre>
       * 时间（起）
       * </pre>
       */
      public int getTimeFrom() {
        return timeFrom_;
      }
      /**
       * <code>optional int32 timeFrom = 1;</code>
       *
       * <pre>
       * 时间（起）
       * </pre>
       */
      public Builder setTimeFrom(int value) {
        bitField0_ |= 0x00000001;
        timeFrom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 timeFrom = 1;</code>
       *
       * <pre>
       * 时间（起）
       * </pre>
       */
      public Builder clearTimeFrom() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timeFrom_ = 0;
        onChanged();
        return this;
      }

      // optional int32 timeTo = 2;
      private int timeTo_ ;
      /**
       * <code>optional int32 timeTo = 2;</code>
       *
       * <pre>
       * 时间（止）
       * </pre>
       */
      public boolean hasTimeTo() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 timeTo = 2;</code>
       *
       * <pre>
       * 时间（止）
       * </pre>
       */
      public int getTimeTo() {
        return timeTo_;
      }
      /**
       * <code>optional int32 timeTo = 2;</code>
       *
       * <pre>
       * 时间（止）
       * </pre>
       */
      public Builder setTimeTo(int value) {
        bitField0_ |= 0x00000002;
        timeTo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 timeTo = 2;</code>
       *
       * <pre>
       * 时间（止）
       * </pre>
       */
      public Builder clearTimeTo() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timeTo_ = 0;
        onChanged();
        return this;
      }

      // optional int32 type = 3;
      private int type_ ;
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 1：充值；2：结单；3：保证金返回；4：提现；5：支付保证金
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.zc.web.message.debt.ListMoneyHistoryReq)
    }

    static {
      defaultInstance = new ListMoneyHistoryReq(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zc.web.message.debt.ListMoneyHistoryReq)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zc_web_message_debt_ListMoneyHistoryReq_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zc_web_message_debt_ListMoneyHistoryReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n?main/resources/com/zc/messages/player/" +
      "ListMoneyHistoryReq.proto\022\027com.zc.web.me" +
      "ssage.debt\"E\n\023ListMoneyHistoryReq\022\020\n\010tim" +
      "eFrom\030\001 \001(\005\022\016\n\006timeTo\030\002 \001(\005\022\014\n\004type\030\003 \001(" +
      "\005B\032B\030ListMoneyHistoryReqProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zc_web_message_debt_ListMoneyHistoryReq_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zc_web_message_debt_ListMoneyHistoryReq_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zc_web_message_debt_ListMoneyHistoryReq_descriptor,
              new java.lang.String[] { "TimeFrom", "TimeTo", "Type", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
