// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/resources/com/zc/messages/debt/MessageMsg.proto

package com.zc.web.message.debt;

public final class MessageMsgProto {
  private MessageMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MessageMsgOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string id = 1;
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * 债务ID
     * </pre>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * 债务ID
     * </pre>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * 债务ID
     * </pre>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    // optional int32 time = 2;
    /**
     * <code>optional int32 time = 2;</code>
     *
     * <pre>
     * 时间
     * </pre>
     */
    boolean hasTime();
    /**
     * <code>optional int32 time = 2;</code>
     *
     * <pre>
     * 时间
     * </pre>
     */
    int getTime();

    // optional int32 type = 3;
    /**
     * <code>optional int32 type = 3;</code>
     *
     * <pre>
     * 类型
     * </pre>
     */
    boolean hasType();
    /**
     * <code>optional int32 type = 3;</code>
     *
     * <pre>
     * 类型
     * </pre>
     */
    int getType();

    // optional string memo = 4;
    /**
     * <code>optional string memo = 4;</code>
     *
     * <pre>
     * 说明
     * </pre>
     */
    boolean hasMemo();
    /**
     * <code>optional string memo = 4;</code>
     *
     * <pre>
     * 说明
     * </pre>
     */
    java.lang.String getMemo();
    /**
     * <code>optional string memo = 4;</code>
     *
     * <pre>
     * 说明
     * </pre>
     */
    com.google.protobuf.ByteString
        getMemoBytes();

    // repeated .com.zc.web.message.common.FileMsg files = 5;
    /**
     * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
     *
     * <pre>
     * 上传文件
     * </pre>
     */
    java.util.List<com.zc.web.message.common.FileMsgProto.FileMsg> 
        getFilesList();
    /**
     * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
     *
     * <pre>
     * 上传文件
     * </pre>
     */
    com.zc.web.message.common.FileMsgProto.FileMsg getFiles(int index);
    /**
     * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
     *
     * <pre>
     * 上传文件
     * </pre>
     */
    int getFilesCount();
    /**
     * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
     *
     * <pre>
     * 上传文件
     * </pre>
     */
    java.util.List<? extends com.zc.web.message.common.FileMsgProto.FileMsgOrBuilder> 
        getFilesOrBuilderList();
    /**
     * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
     *
     * <pre>
     * 上传文件
     * </pre>
     */
    com.zc.web.message.common.FileMsgProto.FileMsgOrBuilder getFilesOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.zc.web.message.debt.MessageMsg}
   */
  public static final class MessageMsg extends
      com.google.protobuf.GeneratedMessage
      implements MessageMsgOrBuilder {
    // Use MessageMsg.newBuilder() to construct.
    private MessageMsg(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MessageMsg(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MessageMsg defaultInstance;
    public static MessageMsg getDefaultInstance() {
      return defaultInstance;
    }

    public MessageMsg getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MessageMsg(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              id_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              time_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              type_ = input.readInt32();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              memo_ = input.readBytes();
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                files_ = new java.util.ArrayList<com.zc.web.message.common.FileMsgProto.FileMsg>();
                mutable_bitField0_ |= 0x00000010;
              }
              files_.add(input.readMessage(com.zc.web.message.common.FileMsgProto.FileMsg.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          files_ = java.util.Collections.unmodifiableList(files_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zc.web.message.debt.MessageMsgProto.internal_static_com_zc_web_message_debt_MessageMsg_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zc.web.message.debt.MessageMsgProto.internal_static_com_zc_web_message_debt_MessageMsg_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zc.web.message.debt.MessageMsgProto.MessageMsg.class, com.zc.web.message.debt.MessageMsgProto.MessageMsg.Builder.class);
    }

    public static com.google.protobuf.Parser<MessageMsg> PARSER =
        new com.google.protobuf.AbstractParser<MessageMsg>() {
      public MessageMsg parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MessageMsg(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MessageMsg> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * 债务ID
     * </pre>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * 债务ID
     * </pre>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     *
     * <pre>
     * 债务ID
     * </pre>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 time = 2;
    public static final int TIME_FIELD_NUMBER = 2;
    private int time_;
    /**
     * <code>optional int32 time = 2;</code>
     *
     * <pre>
     * 时间
     * </pre>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int32 time = 2;</code>
     *
     * <pre>
     * 时间
     * </pre>
     */
    public int getTime() {
      return time_;
    }

    // optional int32 type = 3;
    public static final int TYPE_FIELD_NUMBER = 3;
    private int type_;
    /**
     * <code>optional int32 type = 3;</code>
     *
     * <pre>
     * 类型
     * </pre>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 type = 3;</code>
     *
     * <pre>
     * 类型
     * </pre>
     */
    public int getType() {
      return type_;
    }

    // optional string memo = 4;
    public static final int MEMO_FIELD_NUMBER = 4;
    private java.lang.Object memo_;
    /**
     * <code>optional string memo = 4;</code>
     *
     * <pre>
     * 说明
     * </pre>
     */
    public boolean hasMemo() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string memo = 4;</code>
     *
     * <pre>
     * 说明
     * </pre>
     */
    public java.lang.String getMemo() {
      java.lang.Object ref = memo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          memo_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string memo = 4;</code>
     *
     * <pre>
     * 说明
     * </pre>
     */
    public com.google.protobuf.ByteString
        getMemoBytes() {
      java.lang.Object ref = memo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        memo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated .com.zc.web.message.common.FileMsg files = 5;
    public static final int FILES_FIELD_NUMBER = 5;
    private java.util.List<com.zc.web.message.common.FileMsgProto.FileMsg> files_;
    /**
     * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
     *
     * <pre>
     * 上传文件
     * </pre>
     */
    public java.util.List<com.zc.web.message.common.FileMsgProto.FileMsg> getFilesList() {
      return files_;
    }
    /**
     * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
     *
     * <pre>
     * 上传文件
     * </pre>
     */
    public java.util.List<? extends com.zc.web.message.common.FileMsgProto.FileMsgOrBuilder> 
        getFilesOrBuilderList() {
      return files_;
    }
    /**
     * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
     *
     * <pre>
     * 上传文件
     * </pre>
     */
    public int getFilesCount() {
      return files_.size();
    }
    /**
     * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
     *
     * <pre>
     * 上传文件
     * </pre>
     */
    public com.zc.web.message.common.FileMsgProto.FileMsg getFiles(int index) {
      return files_.get(index);
    }
    /**
     * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
     *
     * <pre>
     * 上传文件
     * </pre>
     */
    public com.zc.web.message.common.FileMsgProto.FileMsgOrBuilder getFilesOrBuilder(
        int index) {
      return files_.get(index);
    }

    private void initFields() {
      id_ = "";
      time_ = 0;
      type_ = 0;
      memo_ = "";
      files_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getMemoBytes());
      }
      for (int i = 0; i < files_.size(); i++) {
        output.writeMessage(5, files_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, time_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, type_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getMemoBytes());
      }
      for (int i = 0; i < files_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, files_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.zc.web.message.debt.MessageMsgProto.MessageMsg parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zc.web.message.debt.MessageMsgProto.MessageMsg parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zc.web.message.debt.MessageMsgProto.MessageMsg parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zc.web.message.debt.MessageMsgProto.MessageMsg parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zc.web.message.debt.MessageMsgProto.MessageMsg parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zc.web.message.debt.MessageMsgProto.MessageMsg parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.zc.web.message.debt.MessageMsgProto.MessageMsg parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.zc.web.message.debt.MessageMsgProto.MessageMsg parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.zc.web.message.debt.MessageMsgProto.MessageMsg parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.zc.web.message.debt.MessageMsgProto.MessageMsg parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.zc.web.message.debt.MessageMsgProto.MessageMsg prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.zc.web.message.debt.MessageMsg}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.zc.web.message.debt.MessageMsgProto.MessageMsgOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zc.web.message.debt.MessageMsgProto.internal_static_com_zc_web_message_debt_MessageMsg_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zc.web.message.debt.MessageMsgProto.internal_static_com_zc_web_message_debt_MessageMsg_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zc.web.message.debt.MessageMsgProto.MessageMsg.class, com.zc.web.message.debt.MessageMsgProto.MessageMsg.Builder.class);
      }

      // Construct using com.zc.web.message.debt.MessageMsgProto.MessageMsg.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getFilesFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        memo_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        if (filesBuilder_ == null) {
          files_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          filesBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zc.web.message.debt.MessageMsgProto.internal_static_com_zc_web_message_debt_MessageMsg_descriptor;
      }

      public com.zc.web.message.debt.MessageMsgProto.MessageMsg getDefaultInstanceForType() {
        return com.zc.web.message.debt.MessageMsgProto.MessageMsg.getDefaultInstance();
      }

      public com.zc.web.message.debt.MessageMsgProto.MessageMsg build() {
        com.zc.web.message.debt.MessageMsgProto.MessageMsg result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zc.web.message.debt.MessageMsgProto.MessageMsg buildPartial() {
        com.zc.web.message.debt.MessageMsgProto.MessageMsg result = new com.zc.web.message.debt.MessageMsgProto.MessageMsg(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.memo_ = memo_;
        if (filesBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            files_ = java.util.Collections.unmodifiableList(files_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.files_ = files_;
        } else {
          result.files_ = filesBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zc.web.message.debt.MessageMsgProto.MessageMsg) {
          return mergeFrom((com.zc.web.message.debt.MessageMsgProto.MessageMsg)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zc.web.message.debt.MessageMsgProto.MessageMsg other) {
        if (other == com.zc.web.message.debt.MessageMsgProto.MessageMsg.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMemo()) {
          bitField0_ |= 0x00000008;
          memo_ = other.memo_;
          onChanged();
        }
        if (filesBuilder_ == null) {
          if (!other.files_.isEmpty()) {
            if (files_.isEmpty()) {
              files_ = other.files_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureFilesIsMutable();
              files_.addAll(other.files_);
            }
            onChanged();
          }
        } else {
          if (!other.files_.isEmpty()) {
            if (filesBuilder_.isEmpty()) {
              filesBuilder_.dispose();
              filesBuilder_ = null;
              files_ = other.files_;
              bitField0_ = (bitField0_ & ~0x00000010);
              filesBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getFilesFieldBuilder() : null;
            } else {
              filesBuilder_.addAllMessages(other.files_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zc.web.message.debt.MessageMsgProto.MessageMsg parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zc.web.message.debt.MessageMsgProto.MessageMsg) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string id = 1;
      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * 债务ID
       * </pre>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * 债务ID
       * </pre>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * 债务ID
       * </pre>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * 债务ID
       * </pre>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * 债务ID
       * </pre>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       *
       * <pre>
       * 债务ID
       * </pre>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      // optional int32 time = 2;
      private int time_ ;
      /**
       * <code>optional int32 time = 2;</code>
       *
       * <pre>
       * 时间
       * </pre>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int32 time = 2;</code>
       *
       * <pre>
       * 时间
       * </pre>
       */
      public int getTime() {
        return time_;
      }
      /**
       * <code>optional int32 time = 2;</code>
       *
       * <pre>
       * 时间
       * </pre>
       */
      public Builder setTime(int value) {
        bitField0_ |= 0x00000002;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 time = 2;</code>
       *
       * <pre>
       * 时间
       * </pre>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0;
        onChanged();
        return this;
      }

      // optional int32 type = 3;
      private int type_ ;
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 类型
       * </pre>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 类型
       * </pre>
       */
      public int getType() {
        return type_;
      }
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 类型
       * </pre>
       */
      public Builder setType(int value) {
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 type = 3;</code>
       *
       * <pre>
       * 类型
       * </pre>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        onChanged();
        return this;
      }

      // optional string memo = 4;
      private java.lang.Object memo_ = "";
      /**
       * <code>optional string memo = 4;</code>
       *
       * <pre>
       * 说明
       * </pre>
       */
      public boolean hasMemo() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string memo = 4;</code>
       *
       * <pre>
       * 说明
       * </pre>
       */
      public java.lang.String getMemo() {
        java.lang.Object ref = memo_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          memo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string memo = 4;</code>
       *
       * <pre>
       * 说明
       * </pre>
       */
      public com.google.protobuf.ByteString
          getMemoBytes() {
        java.lang.Object ref = memo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          memo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string memo = 4;</code>
       *
       * <pre>
       * 说明
       * </pre>
       */
      public Builder setMemo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        memo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string memo = 4;</code>
       *
       * <pre>
       * 说明
       * </pre>
       */
      public Builder clearMemo() {
        bitField0_ = (bitField0_ & ~0x00000008);
        memo_ = getDefaultInstance().getMemo();
        onChanged();
        return this;
      }
      /**
       * <code>optional string memo = 4;</code>
       *
       * <pre>
       * 说明
       * </pre>
       */
      public Builder setMemoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        memo_ = value;
        onChanged();
        return this;
      }

      // repeated .com.zc.web.message.common.FileMsg files = 5;
      private java.util.List<com.zc.web.message.common.FileMsgProto.FileMsg> files_ =
        java.util.Collections.emptyList();
      private void ensureFilesIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          files_ = new java.util.ArrayList<com.zc.web.message.common.FileMsgProto.FileMsg>(files_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.zc.web.message.common.FileMsgProto.FileMsg, com.zc.web.message.common.FileMsgProto.FileMsg.Builder, com.zc.web.message.common.FileMsgProto.FileMsgOrBuilder> filesBuilder_;

      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public java.util.List<com.zc.web.message.common.FileMsgProto.FileMsg> getFilesList() {
        if (filesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(files_);
        } else {
          return filesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public int getFilesCount() {
        if (filesBuilder_ == null) {
          return files_.size();
        } else {
          return filesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public com.zc.web.message.common.FileMsgProto.FileMsg getFiles(int index) {
        if (filesBuilder_ == null) {
          return files_.get(index);
        } else {
          return filesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public Builder setFiles(
          int index, com.zc.web.message.common.FileMsgProto.FileMsg value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.set(index, value);
          onChanged();
        } else {
          filesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public Builder setFiles(
          int index, com.zc.web.message.common.FileMsgProto.FileMsg.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.set(index, builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public Builder addFiles(com.zc.web.message.common.FileMsgProto.FileMsg value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.add(value);
          onChanged();
        } else {
          filesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public Builder addFiles(
          int index, com.zc.web.message.common.FileMsgProto.FileMsg value) {
        if (filesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureFilesIsMutable();
          files_.add(index, value);
          onChanged();
        } else {
          filesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public Builder addFiles(
          com.zc.web.message.common.FileMsgProto.FileMsg.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.add(builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public Builder addFiles(
          int index, com.zc.web.message.common.FileMsgProto.FileMsg.Builder builderForValue) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.add(index, builderForValue.build());
          onChanged();
        } else {
          filesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public Builder addAllFiles(
          java.lang.Iterable<? extends com.zc.web.message.common.FileMsgProto.FileMsg> values) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          super.addAll(values, files_);
          onChanged();
        } else {
          filesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public Builder clearFiles() {
        if (filesBuilder_ == null) {
          files_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          filesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public Builder removeFiles(int index) {
        if (filesBuilder_ == null) {
          ensureFilesIsMutable();
          files_.remove(index);
          onChanged();
        } else {
          filesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public com.zc.web.message.common.FileMsgProto.FileMsg.Builder getFilesBuilder(
          int index) {
        return getFilesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public com.zc.web.message.common.FileMsgProto.FileMsgOrBuilder getFilesOrBuilder(
          int index) {
        if (filesBuilder_ == null) {
          return files_.get(index);  } else {
          return filesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public java.util.List<? extends com.zc.web.message.common.FileMsgProto.FileMsgOrBuilder> 
           getFilesOrBuilderList() {
        if (filesBuilder_ != null) {
          return filesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(files_);
        }
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public com.zc.web.message.common.FileMsgProto.FileMsg.Builder addFilesBuilder() {
        return getFilesFieldBuilder().addBuilder(
            com.zc.web.message.common.FileMsgProto.FileMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public com.zc.web.message.common.FileMsgProto.FileMsg.Builder addFilesBuilder(
          int index) {
        return getFilesFieldBuilder().addBuilder(
            index, com.zc.web.message.common.FileMsgProto.FileMsg.getDefaultInstance());
      }
      /**
       * <code>repeated .com.zc.web.message.common.FileMsg files = 5;</code>
       *
       * <pre>
       * 上传文件
       * </pre>
       */
      public java.util.List<com.zc.web.message.common.FileMsgProto.FileMsg.Builder> 
           getFilesBuilderList() {
        return getFilesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.zc.web.message.common.FileMsgProto.FileMsg, com.zc.web.message.common.FileMsgProto.FileMsg.Builder, com.zc.web.message.common.FileMsgProto.FileMsgOrBuilder> 
          getFilesFieldBuilder() {
        if (filesBuilder_ == null) {
          filesBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.zc.web.message.common.FileMsgProto.FileMsg, com.zc.web.message.common.FileMsgProto.FileMsg.Builder, com.zc.web.message.common.FileMsgProto.FileMsgOrBuilder>(
                  files_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          files_ = null;
        }
        return filesBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.zc.web.message.debt.MessageMsg)
    }

    static {
      defaultInstance = new MessageMsg(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.zc.web.message.debt.MessageMsg)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_zc_web_message_debt_MessageMsg_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_zc_web_message_debt_MessageMsg_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n4main/resources/com/zc/messages/debt/Me" +
      "ssageMsg.proto\022\027com.zc.web.message.debt\032" +
      "3main/resources/com/zc/messages/common/F" +
      "ileMsg.proto\"u\n\nMessageMsg\022\n\n\002id\030\001 \001(\t\022\014" +
      "\n\004time\030\002 \001(\005\022\014\n\004type\030\003 \001(\005\022\014\n\004memo\030\004 \001(\t" +
      "\0221\n\005files\030\005 \003(\0132\".com.zc.web.message.com" +
      "mon.FileMsgB\021B\017MessageMsgProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_zc_web_message_debt_MessageMsg_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_zc_web_message_debt_MessageMsg_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_zc_web_message_debt_MessageMsg_descriptor,
              new java.lang.String[] { "Id", "Time", "Type", "Memo", "Files", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zc.web.message.common.FileMsgProto.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
