package com.zc.web.config.model;

import java.io.Serializable;

public class ConfigCity implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_city.id
     *
     * @mbggenerated Wed May 20 13:57:02 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column config_city.name
     *
     * @mbggenerated Wed May 20 13:57:02 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table config_city
     *
     * @mbggenerated Wed May 20 13:57:02 CST 2015
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_city.id
     *
     * @return the value of config_city.id
     *
     * @mbggenerated Wed May 20 13:57:02 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_city.id
     *
     * @param id the value for config_city.id
     *
     * @mbggenerated Wed May 20 13:57:02 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column config_city.name
     *
     * @return the value of config_city.name
     *
     * @mbggenerated Wed May 20 13:57:02 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column config_city.name
     *
     * @param name the value for config_city.name
     *
     * @mbggenerated Wed May 20 13:57:02 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }
}